services:
  cubyz-map-viewer:
    image: ghcr.io/amerkuri/cubyz-map-viewer:latest
    ports:
      - "3000:3000"
    volumes:
      - /path/to/your/save:/data/save:ro
      - /path/to/Cubyz:/data/cubyz:ro
      - cubyz-map-viewer-logs:/data/logs
      - cubyz-map-viewer-cache:/data/cache
    restart: unless-stopped

volumes:
  cubyz-map-viewer-cache:
  cubyz-map-viewer-logs: