import { encodeBinaryQuads } from "../../../src/server/services/greedy-mesh.js";
import { colors } from "./fixture-world.js";

export function createMixedPayload(): ArrayBuffer {
  return encodeBinaryQuads(
    [
      {
        v0x: 0,
        v0y: 0,
        v0z: 0,
        v1x: 1,
        v1y: 0,
        v1z: 0,
        v2x: 1,
        v2y: 1,
        v2z: 0,
        v3x: 0,
        v3y: 1,
        v3z: 0,
        typ: 1,
        dir: 1,
        packedAo: 0x1b,
        renderKind: 1,
        sourceKind: "greedy",
        face: 5,
        plane: 0,
        u: 0,
        v: 0,
        du: 1,
        dv: 1,
      },
    ],
    [
      {
        v0x: 2.25,
        v0y: 2.25,
        v0z: 0.5,
        v1x: 2.75,
        v1y: 2.25,
        v1z: 0.5,
        v2x: 2.75,
        v2y: 2.75,
        v2z: 1.5,
        v3x: 2.25,
        v3y: 2.75,
        v3z: 1.5,
        typ: 4,
        dir: 0,
        packedAo: 0,
        renderKind: 2,
        sourceKind: "model",
      },
    ],
    128,
    -128,
    32,
    1,
    colors,
    1,
    [
      {
        x: 2,
        y: 2,
        z: 1,
        r: 120,
        g: 200,
        b: 255,
        halo: false,
        openFaces: 0x3f,
        power: 2.5,
        radius: 9,
      },
    ],
  ).buffer;
}
